# Generated by Django 2.0.2 on 2019-03-15 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 20, 3, 23, 955316, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
