# Generated by Django 2.0.2 on 2019-03-15 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190315_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 20, 4, 9, 4147, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
